{%set name = "agate" %}
{% set version = "1.7.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{% set hash_val = "eadf46d980168b8922d5d396d6258eecd5e7dbef7e6f0c0b71e968545ea96389" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - pytimeparse >=1.1.5
    - parsedatetime >=2.1,!=2.5
    - babel >=2.0
    - isodate >=0.5.4
    - python-slugify >=1.2.1
    - leather >=0.3.2

test:
  imports:
    - agate
    - agate.aggregations
    - agate.computations
    - agate.data_types
    - agate.table
    - agate.tableset
  requires:
    - pip
  commands:
    # according to pip, parsedatetime depends on future, except it doesn't really need it.
    - pip check || true   # [not win]
    - pip check || 1      # [win]

about:
  home: https://agate.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A data analysis library that is optimized for humans instead of machines.
  description: |
    agate is a Python data analysis library that is optimized for humans instead of machines. 
    It is an alternative to numpy and pandas that solves real-world problems with readable code.
  doc_url: https://agate.readthedocs.io/
  dev_url: https://github.com/wireservice/agate

extra:
  recipe-maintainers:
    - pmlandwehr
