travis:
  secure:
    BINSTAR_TOKEN: Mo7kh/0EImksntbNQ47anaUKKH1Tlte+eCYFSlSKMY+pC+/yzWCGv8D/0Dfv7BCPTzwpDFdUPgah5YKjjonEZBOOiMuZ07CF2oVEqAWAEVfDOFj9b9OnOvoQsB72qm+POzoQFjAqZMJ1feUWn2mOCCKsXuQL3ZlBxaA6FmYVwSCovN1Kll16SW2djV496foQ/wVRiRzHR9xIYyfG1MGpDvNAHOa491rT1pMr3wSWhcFdcEOhfaP9rBqXs5wM5TGzq5NYzzD1zKKnyhQ9a3oQNBM/cBwWZaXbxWty6mkSOeru1gC/tJaFU8WUffNdrYgxO5Xyz1A/cRraYC+Aw0PtUMo50lvqd3Ghp0MS+7pBzDYoxMkjDmiMMj4LhOaPjRlcKrpwcq0FfVn4ww+s6DLUghreGrAS6YCuXUOwl61jB0on+5Kau+J0o/EfES+bxQYIFaJukbzZNPlOuyxNQPntPcm8t1JwQ+u80yKPRmuXPHdkYKnc2P7sZ/TEMfBCv0ESMzIGJMqfM6CMlpuwLU8CWE82EJu9kMYvczhgzOQiH1vQHv7GoiyafFaVa93ALb5nlilWPkZa7cywoSWjKiGDrRZQJEmdNGTucSWDYdb/CfNX98FWNbDBCk8n+mw+j/6WmTsuWpgwsFvEWBZ9qZZ9kGxn+xV7lv061buD1/y1qKA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
