travis:
  secure:
    BINSTAR_TOKEN: PCCRcXvcFFnVS8J0LU6wIdQrchSKEPK1tt6QwcXA5Ia6yHMIKq6PCVVaF6cbLTy0eIHELewtMVPWUMmS19vuwFSu5ANfP1NBNq1pYsVTXNeXWrnqfM0eZusr6Q6Fn3XoRb4sZ53jmxtywkP52KBFZKcgEqXMl4v4/gYLtFcjJ5WL3SaUCyjDB0YqHD4fMXs5hVh61UwreRy8enaw0w+6zx3h/a2ET/17t1ghtUHM3/RQXyaF6wLP/Msb2WgzH4Tw7fFHCfGd6KT7IoNEBeNIeSHC9D/Qo1yGxYY+LnRtw3Mb/JuO7mq6M3kjmmzu0VobQyp5XMWbv21jR4c4ik6iq3rsJiSlHRgdLXj46rivPrFJwmHTmagzH40EFvdLao2zn3jXAjkIlXZjnd/In4JCPd075pAIlQ0RE2XrctRngcucufVZMcrVqOclgXwioBCvgTieY1Y3Kbnvj0xLEpA3C2pRCk1Vk+rR0fJeHVAMiTU1ADijRbs2uD2aI3s/hvba7RJdidMkw5dDTQRbTFJJput1b0uHjstlKVSwgfLkg/jo/3C4LoeeySdcy2rfmx9FNLAc1DatiHksIKL4B1QLGI3Dmt1N/eCCmkZUNibZzS5mJbcHl1Ku/ghyg0vBWnZ+GLBnTzmzF258DaQYSzSkbXVKvdxgafof+nDxsba7ej4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
